---
name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    name: Run checks and tests over ${{matrix.otp_vsn}} and ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        otp_vsn: [18.3, 19.3, 20.0, 21.0]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - run: rebar3 compile
      - run: rebar3 xref
      - run: rebar3 eunit
      - run: rebar3 dialyzer
      - run: rebar3 edoc
      - run: rebar3 cover
      - run: rebar3 as test covertool generate
      - run: cp _build/test/covertool/hash_ring.covertool.xml ./cobertura.xml
  cov:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - run: sudo pip install codecov
      - run: codecov
